<a href="https://colab.research.google.com/github/Hujaifa98/AIProjects/blob/main/Tensorflow_data_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
tf.constant([[1.,2.,3.],[4.,5.,6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [ ]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t @ tf.transpose(t) # @ = matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.reshape(t,[6])

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [ ]:
tf.squeeze(tf.constant([1, 2, 1, 3, 1, 1]))

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 1, 3, 1, 1], dtype=int32)>

In [ ]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

In [ ]:
tf.reduce_sum(t)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [ ]:
tf.math.log(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595]], dtype=float32)>

In [ ]:
a = np.array([2.,3.,4.,5.])
tf.constant(a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 3., 4., 5.])>

In [ ]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
tf.square(a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 4.,  9., 16., 25.])>

In [ ]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [ ]:
tf.constant(2.) + tf.constant(40.,dtype=tf.float64)
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: ignored

In [ ]:
t2 = tf.constant(40.,dtype=tf.float64)
tf.constant(2.) + tf.cast(t2,dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [ ]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
v[0,2].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4., 42.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
daily_sales_number =[21,22,-108,31,-1,32,34,31]

In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
for sales in tf_dataset:
  print(sales)
for sales in tf_dataset:
  print(sales.numpy())

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
21
22
-108
31
-1
32
34
31


In [ ]:
for sales in tf_dataset.take(3) :
  print(sales.numpy())


21
22
-108


In [ ]:
tf_dataset = tf_dataset.filter(lambda x:x>=0)

In [ ]:
for sales in tf_dataset:
  print(sales.numpy())

21
22
31
32
34
31


In [ ]:
tf_dataset = tf_dataset.map(lambda x: x*81)
for sales in tf_dataset:
  print(sales.numpy())

1701
1782
2511
2592
2754
2511


In [ ]:
tf_dataset = tf_dataset.shuffle(3)
for sales in tf_dataset:
  print(sales.numpy())

1782
2511
2592
1701
2754
2511


In [ ]:
x = tf_dataset.batch(3)

In [ ]:
for batch in x:
  print(batch)

tf.Tensor([1782 2592 2511], shape=(3,), dtype=int32)
tf.Tensor([2511 2754 1701], shape=(3,), dtype=int32)


In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset = tf_dataset.filter(lambda x:x>=0).map(lambda y:y*81).shuffle(3).batch(2)
for sales in tf_dataset:
  print(sales.numpy())

[1701 1782]
[2511 2592]
[2754 2511]


In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_number)
train_size = int(len(tf_dataset) * 0.8)
train_ds = tf_dataset.take(train_size)
test_ds = tf_dataset.skip(train_size)

In [ ]:
print('Train')
for sales in train_ds:
  print(sales.numpy())
print('Test')
for sales in test_ds:
  print(sales.numpy())

Train
21
22
-108
31
-1
32
Test
34
31


In [ ]:
s = 'images\\dog\\mydog.jpg'
s.split('\\')[1]

'dog'

In [ ]:
class FileDataset(tf.data.Dataset):
  def read_files_in_batches(num_samples):
    #open file
    time.sleep(0.03)
    for sample_idx in range(num_samples):
      #read file
      time.sleep(0.015)
      yield (sample_idx,)
  def __new__(cls , num_samples=3):
    return tf.data.Dataset.from_generator(
        cls.read_files_in_batches,
        output_signature = tf.TensorSpec(shape=(1,),dtype=tf.int64),
        args = (num_samples,)
    )

In [ ]:
def benchmark(dataset,num_epochs=2):
  for epoch_num in range(num_epochs):
    for sample in dataset:
      #train file
      time.sleep(0.01)

In [ ]:
%%timeit
benchmark(FileDataset())

1 loop, best of 5: 289 ms per loop


In [ ]:
%%timeit
benchmark(FileDataset().prefetch(1))

1 loop, best of 5: 246 ms per loop


In [ ]:
%%timeit
benchmark(FileDataset().prefetch(tf.data.AUTOTUNE))

1 loop, best of 5: 244 ms per loop


In [ ]:
dataset = tf.data.Dataset.range(5)
for items in dataset:
  print(items.numpy())

0
1
2
3
4


In [ ]:
dataset = dataset.map(lambda x:x**2)
for items in dataset:
  print(items.numpy())

0
1
4
9
16


In [ ]:
dataset = dataset.cache()

In [ ]:
def mapped_function(s):
  tf.py_function(lambda : time.sleep(0.03),[],())  
  return s

In [ ]:
%%timeit -n1 -r1
benchmark(FileDataset().map(mapped_function) , 5)

1 loop, best of 1: 1.23 s per loop


In [ ]:
%%timeit -n1 -r1
benchmark(FileDataset().map(mapped_function).prefetch(tf.data.AUTOTUNE).cache() , 5)

1 loop, best of 1: 526 ms per loop


In [ ]:
X = tf.range(10)
X.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
for nums in dataset:
  print(nums.numpy())

0
1
2
3
4
5
6
7
8
9


In [ ]:
dataset = dataset.repeat(3)
for nums in dataset:
  print(nums.numpy())

0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9


In [ ]:
dataset = dataset.batch(7,drop_remainder=True)
for nums in dataset:
  print(nums.numpy())

[0 1 2 3 4 5 6]
[7 8 9 0 1 2 3]
[4 5 6 7 8 9 0]
[1 2 3 4 5 6 7]


In [ ]:
dataset = dataset.map(lambda x:x*2)
for nums in dataset:
  print(nums.numpy())

[ 0  2  4  6  8 10 12]
[14 16 18  0  2  4  6]
[ 8 10 12 14 16 18  0]
[ 2  4  6  8 10 12 14]


In [ ]:
for nums in dataset.take(3):
  print(nums)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)


In [ ]:
for nums in dataset.skip(3):
  print(nums)

tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)


In [ ]:
dataset = dataset.shuffle(7)
for nums in dataset:
  print(nums)

tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)


In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_

In [ ]:
def save_to_multiple_csv_files(data, name_prefix, header=None, n_parts=10):
    housing_dir = os.path.join("datasets", "housing")
    os.makedirs(housing_dir, exist_ok=True)
    path_format = os.path.join(housing_dir, "my_{}_{:02d}.csv")

    filepaths = []
    m = len(data)
    for file_idx, row_indices in enumerate(np.array_split(np.arange(m), n_parts)):
        part_csv = path_format.format(name_prefix, file_idx)
        filepaths.append(part_csv)
        with open(part_csv, "wt", encoding="utf-8") as f:
            if header is not None:
                f.write(header)
                f.write("\n")
            for row_idx in row_indices:
                f.write(",".join([repr(col) for col in data[row_idx]]))
                f.write("\n")
    return filepaths

In [ ]:
import os
train_data = np.c_[X_train, y_train]
valid_data = np.c_[X_valid, y_valid]
test_data = np.c_[X_test, y_test]
header_cols = housing.feature_names + ["MedianHouseValue"]
header = ",".join(header_cols)

train_filepaths = save_to_multiple_csv_files(train_data, "train", header, n_parts=20)
valid_filepaths = save_to_multiple_csv_files(valid_data, "valid", header, n_parts=10)
test_filepaths = save_to_multiple_csv_files(test_data, "test", header, n_parts=10)

In [ ]:
import pandas as pd

pd.read_csv(train_filepaths[0]).head()

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedianHouseValue
0  3.5214      15.0  3.049945  ...     37.63    -122.43             1.442
1  5.3275       5.0  6.490060  ...     33.69    -117.39             1.687
2  3.1000      29.0  7.542373  ...     38.44    -122.98             1.621
3  7.1736      12.0  6.289003  ...     33.55    -117.70             2.621
4  2.0549      13.0  5.312457  ...     33.93    -116.93             0.956

[5 rows x 9 columns]

In [ ]:
import pandas as pd

pd.read_csv(train_filepaths[0]).head()

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedianHouseValue
0  3.5214      15.0  3.049945  ...     37.63    -122.43             1.442
1  5.3275       5.0  6.490060  ...     33.69    -117.39             1.687
2  3.1000      29.0  7.542373  ...     38.44    -122.98             1.621
3  7.1736      12.0  6.289003  ...     33.55    -117.70             2.621
4  2.0549      13.0  5.312457  ...     33.93    -116.93             0.956

[5 rows x 9 columns]

In [ ]:
train_filepaths

['datasets/housing/my_train_00.csv',
 'datasets/housing/my_train_01.csv',
 'datasets/housing/my_train_02.csv',
 'datasets/housing/my_train_03.csv',
 'datasets/housing/my_train_04.csv',
 'datasets/housing/my_train_05.csv',
 'datasets/housing/my_train_06.csv',
 'datasets/housing/my_train_07.csv',
 'datasets/housing/my_train_08.csv',
 'datasets/housing/my_train_09.csv',
 'datasets/housing/my_train_10.csv',
 'datasets/housing/my_train_11.csv',
 'datasets/housing/my_train_12.csv',
 'datasets/housing/my_train_13.csv',
 'datasets/housing/my_train_14.csv',
 'datasets/housing/my_train_15.csv',
 'datasets/housing/my_train_16.csv',
 'datasets/housing/my_train_17.csv',
 'datasets/housing/my_train_18.csv',
 'datasets/housing/my_train_19.csv']

In [ ]:
filepath_dataset = tf.data.Dataset.list_files(train_filepaths,seed=42)
for paths in filepath_dataset:
  print(paths.numpy())

b'datasets/housing/my_train_05.csv'
b'datasets/housing/my_train_16.csv'
b'datasets/housing/my_train_01.csv'
b'datasets/housing/my_train_17.csv'
b'datasets/housing/my_train_00.csv'
b'datasets/housing/my_train_14.csv'
b'datasets/housing/my_train_10.csv'
b'datasets/housing/my_train_02.csv'
b'datasets/housing/my_train_12.csv'
b'datasets/housing/my_train_19.csv'
b'datasets/housing/my_train_07.csv'
b'datasets/housing/my_train_09.csv'
b'datasets/housing/my_train_13.csv'
b'datasets/housing/my_train_15.csv'
b'datasets/housing/my_train_11.csv'
b'datasets/housing/my_train_18.csv'
b'datasets/housing/my_train_04.csv'
b'datasets/housing/my_train_06.csv'
b'datasets/housing/my_train_03.csv'
b'datasets/housing/my_train_08.csv'


In [ ]:
x = tf.data.TextLineDataset(filepath_dataset)
for paths in x.take(5):
  print(paths.numpy())

b'MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedianHouseValue'
b'3.9688,41.0,5.259786476868327,0.9715302491103203,916.0,3.2597864768683276,33.98,-118.07,1.698'
b'2.7344,18.0,7.085158150851582,1.6131386861313868,999.0,2.4306569343065694,38.42,-120.42,0.919'
b'5.6013,35.0,5.771428571428571,0.9938775510204082,1439.0,2.936734693877551,33.83,-118.36,3.502'
b'6.3767,24.0,6.37987012987013,1.073051948051948,1831.0,2.9724025974025974,33.67,-117.81,2.69'


In [ ]:
n_reader=5
dataset = filepath_dataset.interleave(lambda x:tf.data.TextLineDataset(filepath_dataset).skip(1) , cycle_length=n_reader)
for items in dataset.take(5):
  print(items.numpy())

b'5.9522,26.0,6.196521739130435,1.0069565217391305,1479.0,2.5721739130434784,34.5,-119.75,4.384'
b'3.6875,44.0,4.524475524475524,0.993006993006993,457.0,3.195804195804196,34.04,-118.15,1.625'
b'3.6875,44.0,4.524475524475524,0.993006993006993,457.0,3.195804195804196,34.04,-118.15,1.625'
b'4.5909,16.0,5.475877192982456,1.0964912280701755,1357.0,2.9758771929824563,33.63,-117.71,2.418'
b'1.6571,34.0,4.454976303317536,1.0876777251184835,1358.0,3.2180094786729856,37.94,-122.35,1.052'


In [ ]:
n_inputs = 8
def preprocess(line):
  defs = [0.] * n_inputs + [tf.constant([],dtype=tf.float32)]
  fields = tf.io.decode_csv(line,record_defaults=defs)
  x = tf.stack(fields[:-1])
  y = tf.stack(fields[-1:])
  return (x - X_mean) / X_std , y


In [ ]:
preprocess(b'4.2083,44.0,5.3232,0.9171,846.0,2.3370,37.47,-122.2,2.782')

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([ 0.16579159,  1.216324  , -0.05204564, -0.39215982, -0.5277444 ,
        -0.2633488 ,  0.8543046 , -1.3072058 ], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.782], dtype=float32)>)

In [ ]:
def csv_reader_datset(filepaths,repeat=1,n_readers=5,n_read_threads=None,shuffle_buffer_size=10000,n_parse_threads=5,batch_size=32):
  dataset = tf.data.Dataset.list_files(filepaths)
  dataset = dataset.interleave(lambda x:tf.data.TextLineDataset(filepaths).skip(1) , cycle_length=n_readers , num_parallel_calls=n_read_threads)
  dataset = dataset.map(preprocess,num_parallel_calls=n_read_threads)
  dataset = dataset.shuffle(shuffle_buffer_size).repeat(repeat)
  dataset = dataset.batch(batch_size)
  dataset = dataset.prefetch(tf.data.AUTOTUNE)
  return dataset